/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT app.cdb */

#define CHIP_5402 1

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <log.h>
#include <pip.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj swiRxSplit;
extern SWI_Obj swiAudioproc0;
extern SWI_Obj swiAudioproc1;
extern SWI_Obj swiTxJoin;
extern SWI_Obj swiControl;
extern LOG_Obj LOG_system;
extern LOG_Obj logTrace;
extern PIP_Obj pipRx;
extern PIP_Obj pipRx0;
extern PIP_Obj pipTx0;
extern PIP_Obj pipRx1;
extern PIP_Obj pipTx1;
extern PIP_Obj pipTx;
extern STS_Obj IDL_busyObj;
extern STS_Obj stsTime0;
extern STS_Obj stsTime1;
extern STS_Obj stsTime2;
extern STS_Obj stsTime3;
extern STS_Obj stsTime4;
extern STS_Obj stsTime5;
extern STS_Obj stsTime6;
extern STS_Obj stsTime7;
extern STS_Obj stsTime8;
extern STS_Obj stsTime9;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
