timake src/fir_ti/fir_ti54.pjt DEBUG -a
timake src/fir_ti/fir_ti54f.pjt DEBUG -a
timake src/fir_ti/fir_ti55.pjt DEBUG -a
timake src/fir_ti/fir_ti55l.pjt DEBUG -a
timake src/algmin/algmin54.pjt DEBUG -a
timake src/algmin/algmin54f.pjt DEBUG -a
timake src/algmin/algmin55.pjt DEBUG -a
timake src/algmin/algmin55l.pjt DEBUG -a
timake src/utl/utl54.pjt DEBUG -a
timake src/utl/utl54f.pjt DEBUG -a
timake src/utl/utl55.pjt DEBUG -a
timake src/utl/utl55l.pjt DEBUG -a
timake src/algrf/algrf54.pjt DEBUG -a
timake src/algrf/algrf54f.pjt DEBUG -a
timake src/algrf/algrf55.pjt DEBUG -a
timake src/algrf/algrf55l.pjt DEBUG -a
timake src/vol_ti/vol_ti54.pjt DEBUG -a
timake src/vol_ti/vol_ti54f.pjt DEBUG -a
timake src/vol_ti/vol_ti55.pjt DEBUG -a
timake src/vol_ti/vol_ti55l.pjt DEBUG -a
timake src/chan/chan54.pjt DEBUG -a
timake src/chan/chan54f.pjt DEBUG -a
timake src/chan/chan55.pjt DEBUG -a
timake src/chan/chan55l.pjt DEBUG -a
timake src/icc/icc54.pjt DEBUG -a
timake src/icc/icc54f.pjt DEBUG -a
timake src/icc/icc55.pjt DEBUG -a
timake src/icc/icc55l.pjt DEBUG -a
timake src/scom/scom54.pjt DEBUG -a
timake src/scom/scom54f.pjt DEBUG -a
timake src/scom/scom55.pjt DEBUG -a
timake src/scom/scom55l.pjt DEBUG -a
timake src/sscr/sscr54.pjt DEBUG -a
timake src/sscr/sscr54f.pjt DEBUG -a
timake src/sscr/sscr55.pjt DEBUG -a
timake src/sscr/sscr55l.pjt DEBUG -a
timake src/msglink/msglink54.pjt DEBUG -a
timake src/msglink/msglink54f.pjt DEBUG -a
timake src/msglink/msglink55.pjt DEBUG -a
timake src/msglink/msglink55l.pjt DEBUG -a
timake src/c55xx_dma_mcbsp_cslv3/c5910_dma_mcbsp_cslv3.pjt DEBUG -a
timake src/c55xx_dma_mcbsp_cslv3/c5912_dma_mcbsp_cslv3.pjt DEBUG -a
timake src/innov5910_dma_aic23_cslv3/innov5910_dma_aic23_cslv3.pjt DEBUG -a
timake src/osk5912_dma_aic23_cslv3/osk5912_dma_aic23_cslv3.pjt DEBUG -a
timake apps/rf1/dsk5402/rf1.pjt DEBUG -a
timake apps/rf1/dsk5416/rf1.pjt DEBUG -a
timake apps/rf1/dsk5510/rf1.pjt DEBUG -a
timake apps/rf1/genbufs/dsk5402/genbufs.pjt DEBUG -a
timake apps/rf1/genbufs/dsk5416/genbufs.pjt DEBUG -a
timake apps/rf1/genbufs/dsk5510/genbufs.pjt DEBUG -a
timake apps/rf3/dsk5402/app.pjt DEBUG -a
timake apps/rf3/dsk5416/app.pjt DEBUG -a
timake apps/rf3/dsk5510/app.pjt DEBUG -a
timake apps/rf5/projects/dsk5510/app.pjt DEBUG -a
timake apps/rf6/projects/innovator1510/app.pjt DEBUG -a
timake apps/rf6/projects/osk5912/app.pjt DEBUG -a
