timake src/fir_ti/fir_ti62.pjt DEBUG -a
timake src/fir_ti/fir_ti64.pjt DEBUG -a
timake src/algmin/algmin62.pjt DEBUG -a
timake src/algmin/algmin64.pjt DEBUG -a
timake src/utl/utl62.pjt DEBUG -a
timake src/utl/utl64.pjt DEBUG -a
timake src/algrf/algrf62.pjt DEBUG -a
timake src/algrf/algrf64.pjt DEBUG -a
timake src/vol_ti/vol_ti62.pjt DEBUG -a
timake src/vol_ti/vol_ti64.pjt DEBUG -a
timake src/chan/chan62.pjt DEBUG -a
timake src/chan/chan64.pjt DEBUG -a
timake src/icc/icc62.pjt DEBUG -a
timake src/icc/icc64.pjt DEBUG -a
timake src/scom/scom62.pjt DEBUG -a
timake src/scom/scom64.pjt DEBUG -a
timake src/sscr/sscr62.pjt DEBUG -a
timake src/sscr/sscr64.pjt DEBUG -a
timake src/msglink/msglink62.pjt DEBUG -a
timake src/msglink/msglink64.pjt DEBUG -a
timake apps/rf1/genbufs/dsk6x11/genbufs.pjt DEBUG -a
timake apps/rf3/dsk6x11/app.pjt DEBUG -a
timake apps/rf3/teb6416/app.pjt DEBUG -a
timake apps/rf3/dsk6416/app.pjt DEBUG -a
timake apps/rf3/dsk6713/app.pjt DEBUG -a
timake apps/rf5/projects/teb6416/app.pjt DEBUG -a
timake apps/rf5/projects/dsk6416/app.pjt DEBUG -a
timake apps/rf5/projects/dsk6713/app.pjt DEBUG -a
