/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT app.cdb */

#define CHIP_6211 1

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <log.h>
#include <pip.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far HST_Obj RTA_fromHost;
extern far HST_Obj RTA_toHost;
extern far SWI_Obj swiRxSplit;
extern far SWI_Obj swiAudioproc0;
extern far SWI_Obj swiAudioproc1;
extern far SWI_Obj swiTxJoin;
extern far SWI_Obj swiControl;
extern far LOG_Obj LOG_system;
extern far LOG_Obj logTrace;
extern far PIP_Obj pipRx;
extern far PIP_Obj pipRx0;
extern far PIP_Obj pipTx0;
extern far PIP_Obj pipRx1;
extern far PIP_Obj pipTx1;
extern far PIP_Obj pipTx;
extern far STS_Obj IDL_busyObj;
extern far STS_Obj stsTime0;
extern far STS_Obj stsTime1;
extern far STS_Obj stsTime2;
extern far STS_Obj stsTime3;
extern far STS_Obj stsTime4;
extern far STS_Obj stsTime5;
extern far STS_Obj stsTime6;
extern far STS_Obj stsTime7;
extern far STS_Obj stsTime8;
extern far STS_Obj stsTime9;
extern far void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
