/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT rf1.cdb */

#define CHIP_5402 1

/*  Include Header Files  */
#include <std.h>
#include <log.h>
#include <pip.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern LOG_Obj LOG_system;
extern LOG_Obj trace;
extern PIP_Obj pipRx;
extern PIP_Obj pipTx;
extern STS_Obj audioProcessExecTime;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
