#   ============================================================================
#   @file   Makefile
#
#   @path   $(DSPLINK)\gpp\src\test
#
#   @desc   This file is a standard interface to the make scripts.
#           Usually no change is required in this file.
#
#           To change the way a component is built edit the corresponding
#           COMPONENT file.
#
#   @ver    01.10.01
#   ============================================================================
#   Copyright (c) Texas Instruments Incorporated 2002-2004
#
#   Use of this software is controlled by the terms and conditions found in the
#   license agreement under which this software has been supplied or provided.
#   ============================================================================


#   ============================================================================
#   Get the directory separator used on the development host.
#   ============================================================================

ifneq ("$(ComSpec)", "")
DIRSEP ?=\\
else
DIRSEP ?= /
endif


#   ============================================================================
#   Start the build process
#   ============================================================================

include $(DSPLINK)$(DIRSEP)gpp$(DIRSEP)make$(DIRSEP)start.mk
