/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT genbufs.cdb */

#define CHIP_5416 1

/*  Include Header Files  */
#include <std.h>
#include <log.h>

#ifdef __cplusplus
extern "C" {
#endif

extern LOG_Obj LOG_system;
extern LOG_Obj MOD_xdasBufSrcTrace;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
