#!/bin/sh -f
#   ============================================================================
#   @file   dsplinkcfg
#
#   @path   $(DSPLINK)/etc/host/scripts/Linux
#
#   @desc   Calls perl script to create build configuration for
#           DSP/BIOS(TM) Link
#
#   @ver    01.10.01
#   ============================================================================
#   Copyright (c) Texas Instruments Incorporated 2002-2004
#
#   Use of this software is controlled by the terms and conditions found in the
#   license agreement under which this software has been supplied or provided.
#   ============================================================================

pushd $DSPLINK/config/bin
perl  dsplinkcfg.pl
popd
