/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT ReceiveMsg_bios_text.cdb */

/*  Include Header Files  */
#include <std.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>

#ifdef __cplusplus
extern "C" {
#endif

extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern LOG_Obj LOG_system;
extern LOG_Obj trace;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
