/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT app.cdb */

#define CHIP_5510PG2_2 1

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sts.h>
#include <csl_emif.h>

#ifdef __cplusplus
extern "C" {
#endif

extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj tskRxSplit;
extern TSK_Obj tskTxJoin;
extern TSK_Obj tskProcess;
extern TSK_Obj tskControl;
extern LOG_Obj LOG_system;
extern LOG_Obj logTrace;
extern STS_Obj IDL_busyObj;
extern STS_Obj stsTime0;
extern STS_Obj stsTime1;
extern STS_Obj stsTime2;
extern STS_Obj stsTime3;
extern STS_Obj stsTime4;
extern STS_Obj stsTime5;
extern STS_Obj stsTime6;
extern STS_Obj stsTime7;
extern STS_Obj stsTime8;
extern STS_Obj stsTime9;
extern EMIF_Config emifCfg0;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
