/*
 *  Copyright 2003 by Texas Instruments Incorporated.
 *  All rights reserved. Property of Texas Instruments Incorporated.
 *  Restricted rights to use, duplicate or disclose this code are
 *  granted through contract.
 *  
 */
/* "@(#) ReferenceFrameworks 3.10.00.05 04-29-04 (swat-g05)" */
/* 
 * This file is generated by the XDAIS static pre-program. It creates the 
 * buffers requested by the algorithm with the requested size, alignment, 
 * and also provides a subsection for linker placement 
 */ 

#include <std.h>

#pragma DATA_SECTION(firChanBufId00, ".bss:firChanBufId00") 
#pragma DATA_ALIGN(firChanBufId00, 4)

#pragma DATA_SECTION(firChanBufId01, ".bss:firChanBufId01") 
#pragma DATA_ALIGN(firChanBufId01, 2)

#pragma DATA_SECTION(firChanBufId02Scr, ".bss:firChanBufId02Scr") 
#pragma DATA_ALIGN(firChanBufId02Scr, 2)

Char firChanBufId00[6];
Char firChanBufId01[31];
Char firChanBufId02Scr[287];


