/*
 *  Copyright 2003 by Texas Instruments Incorporated.
 *  All rights reserved. Property of Texas Instruments Incorporated.
 *  Restricted rights to use, duplicate or disclose this code are
 *  granted through contract.
 *  
 */
/* "@(#) ReferenceFrameworks 3.10.00.05 04-29-04 (swat-g05)" */
/*
 *  ======== genbufs.c ========
 *  
 *  Generates a minimum static buffer configuration for running an XDAIS
 *  algorithm in a static data memory system.
 *
 *  Intention is that this be used as a pre-program. It generates
 *  a LOG buffer output which can be set to write to a file.
 *  The file created is a valid C source file which can then be included
 *  in the user's end-application to auto-setup the buffers required by the
 *  XDAIS algorithm. The buffers will have the correct size, alignment etc
 *  as requested by the algorithm's algAlloc method.
 */

#include <std.h>
#include <log.h>

#include <ialg.h>

#include <stdlib.h>                 // to support exit() function

/* User should modify this file to pre-gen XDAIS buffers for their algorithm */
#include "mod_configure.h"


/* Stringification - create preprocessor strings inside a string */
#define MODSTR(s)           XMODSTR(s)
#define XMODSTR(s)          #s

#define MAXNUMRECS          16

/* macros to avoid duplication in coding and clarify intent */
#define DATASECTIONSTR1 \
        "#pragma DATA_SECTION(" MODSTR(MODULENAME) "ChanBufId" "%02x"
#define DATASECTIONSTR2 \
        ", \".bss:" MODSTR(MODULENAME) "ChanBufId" "%02x"

#define DATAALIGNSTR    \
        "#pragma DATA_ALIGN(" MODSTR(MODULENAME) "ChanBufId" "%02x"

#define BUFFERDECLSTR   \
        "Char " MODSTR(MODULENAME) "ChanBufId" "%02x"


/* local function prototypes */
static Int memTabCreate(IALG_Fxns *fxns, IALG_Params *params);


/* data references and definitions */
extern LOG_Obj  MOD_xdasBufSrcTrace;

extern IALG_Fxns    MOD_VEN_IALG;
extern IALG_Params *MOD_chanParamPtrs[];

IALG_MemRec memTab[MAXNUMRECS]; /* XDAIS Mem Tab structure declaration */

/*
 *  ======== main ========
 */
Void main()
{
    Int numRecs;
    Int i, chan;
    Int chanBufId;
    
    /* generate comments for the output C source program */
    LOG_printf(&MOD_xdasBufSrcTrace, "/* \
\n * This file is generated by the XDAIS static pre-program. It creates the \
\n * buffers requested by the algorithm with the requested size, alignment, \
\n * and also provides a subsection for linker placement \
\n */ \n");

    /* generate the include of standard portable types */
    LOG_printf(&MOD_xdasBufSrcTrace, "#include <std.h>" "\n");
    
    for (chan=0; chan < NUMCHANNELS; chan++) {
        
        /* Get the algorithm's buffer requirements e.g. size, alignment */
        numRecs = memTabCreate(&MOD_VEN_IALG, MOD_chanParamPtrs[chan]);     
        
        if (numRecs != IALG_EFAIL) {
        
            for (i=0; i<numRecs; i++) { 
            
                /* chanBufId is a 'mask' of chan # and memTab[] index */
                chanBufId = (chan << 4) | i;        
            
                if (memTab[i].attrs == IALG_SCRATCH) {              
                    LOG_printf(&MOD_xdasBufSrcTrace, DATASECTIONSTR1 "Scr" DATASECTIONSTR2 "Scr" "\") ", chanBufId, chanBufId);
                    LOG_printf(&MOD_xdasBufSrcTrace, DATAALIGNSTR "Scr" ", %d)" "\n", chanBufId, memTab[i].alignment);  
                }
                else {
                    LOG_printf(&MOD_xdasBufSrcTrace, DATASECTIONSTR1       DATASECTIONSTR2       "\") ", chanBufId, chanBufId);
                    LOG_printf(&MOD_xdasBufSrcTrace, DATAALIGNSTR       ", %d)" "\n", chanBufId, memTab[i].alignment);  
                }           
            }
            
            /* Declare the static XDAIS buffer variables with correct size */
            for (i=0; i<numRecs; i++) { 
            
                /* chanBufId is a 'mask' of chan # and memTab[] index */
                chanBufId = (chan << 4) | i;                
            
                if (memTab[i].attrs == IALG_SCRATCH) {
                    LOG_printf(&MOD_xdasBufSrcTrace, BUFFERDECLSTR "Scr" "[%d];", chanBufId, memTab[i].size);
                }
                else {
                    LOG_printf(&MOD_xdasBufSrcTrace, BUFFERDECLSTR       "[%d];", chanBufId, memTab[i].size);
                }               
            }
        
        } /* end if (numRecs != IALG_EFAIL) */
        else {
            /* Fail. Error flagged will prevent end-application compilation */
            LOG_printf(&MOD_xdasBufSrcTrace, "#error : Failed to create necessary static data structures");     
        }
                
        LOG_printf(&MOD_xdasBufSrcTrace, "\n");

    } /* end of channel for loop */

    /* 
     *  Normal procedure is to call return; at end of main and fall into the 
     *  DSP/BIOS IDL loop. However, we want to terminate the pre-program here
     *  hence we simply call exit with a normal status code.
     */
    exit(0);
    
} /* end main */

/*
 *  ======== memTabCreate ========
 */
static Int memTabCreate(IALG_Fxns *fxns, IALG_Params *params)
{
    Int n;
    IALG_Fxns *fxnsPtr;    

    if (fxns != NULL) {
        n = (fxns->algNumAlloc != NULL) ? (fxns->algNumAlloc()) 
                                        : IALG_DEFMEMRECS;

        if (n < MAXNUMRECS) {

            /* get the buffer requirements e.g. size, alignment */
            n = fxns->algAlloc(params, &fxnsPtr, memTab);
            if (n <= 0) {
                return (IALG_EFAIL);
            }
        }
        else {                  /* invalid number of Memory Descriptors */
            return (IALG_EFAIL);
        }
    }
   
    return (n);

} /* end memTabCreate */


