/*
 * FILENAME: prog1.c
 *
 * Copyright Empower Technologies Incorporated 2005.
 * All Rights Reserved.
 * #405 - 5600 Parkwood Way, 
 * Crestwood Commerce Centre,
 * Richmond, B.C., Canada V6V 2M2
 *
 * The copyright to this source code and application(s) herein is the
 * property of Empower Technologies Inc, Canada. This source code and
 * or the applications may be used modified or copied only with written
 * permission of Empower Technologies or in accordance with the terms
 * and conditions stipulated in the agreement or contract under which
 * this source and or application have been supplied. This copyright
 * notice must not be removed.
 *
 * Author(s): Empower Technologies Incorporated
 *
 * Initially Released: April 15, 2005    Build/Version: 1.0
 * Initial release target: EPT_LDK_5912
 *
 * Description:
 * Program 1 is a very simple introduction to forms and GUI messages. 
 * It demonstrates the use of the form components caption, label and button, 
 * and the GUI messages generated by a button click.
 *
 */


#include <unistd.h>
#include "linux/gui.h"
#include <pthread.h>
#include "prog1c.rsrc"
//#include "wave_recorder.h"



#define MENU_FILE 		10
#define MENUITEM_EXIT		12
#define IDD_TEST		30
#define IDD_TEST1		40
#define START                   50
#define REC                     60
#define STOP                    70
#define PLAY                    80   

static FORMCAPTION frm_caption={"Sample",NULL};

static FORM frmSample[]={
	{FORM_CAPTION,0,0,0,SCREEN_WIDTH,SCREEN_HEIGHT-TASKBAR_HEIGHT,&frm_caption,FORM_FRAME_CAPTION,0,0},
	{FORM_MENU,MENU_FILE,5,20,0,0,"File",0,COMPONENT_VISIBLE},
	{FORM_MENUITEM,MENUITEM_EXIT,5,20,0,0,"Exit",0},
        {FORM_BUTTON,START,4,270,37,22,"INIT",0,COMPONENT_VISIBLE,FONT_SMALL},
        {FORM_BUTTON,REC,43,270,37,22,"EXE",0,COMPONENT_VISIBLE,FONT_SMALL},
        {FORM_BUTTON,STOP,82,270,37,22,"STOP",0,COMPONENT_VISIBLE,FONT_SMALL},
        {FORM_BUTTON,PLAY,199,270,37,22,"PLAY",0,COMPONENT_VISIBLE,FONT_SMALL},
        {FORM_END},
};
	

int dumb=1;
pthread_t pid;

void ShowSample(void); 
void wait_loop(void);

int main(int argc,char *argv[])
{	 
	short launch_cmd;

	launch_cmd = GetLaunchCommand(argc,argv);
	init_screen(launch_cmd);

	switch (launch_cmd)
	{
		case CMD_RUN_NORMAL:
			ShowSample();
		break;
		case CMD_RUN_GET_INFO:
			PutAppInfo(&app_info);
		break;
	        case CMD_RUN_GET_VERSION:
			PutVersionInfo(&app_info);
		break; 
	}   
	close_screen();
	return 0;
}

void ShowSample(void)
{
	ClearMessageQueue();
	CreateForm(frmSample);
	wait_loop();
}		

void wait_loop(void)
{
	GUI_MSG msg;
	U8 Flag=1;
        //int argc;
        //char *argv[4];
	
	while (Flag) {
		GetMessage(frmSample,&msg);
		switch (msg.event) {
			case EVENT_KEYUP:
				switch(msg.keycode)
					{
					case KEY_RETURN:
					  Flag=0;			 
	 				break;

					default:
					        DefaultMessageRoutine(frmSample,&msg);
					}
			break ;
				
			case EVENT_CLICK:
				switch (msg.id) {
					case MENUITEM_EXIT:	//Close dialog and go out
						Flag = 0;
						CloseForm(frmSample);
					break;

					 case START:
                                                printf("\nINIT button Pressed\n");
                                               // wave_rec_main();
                                                LOOP_Create ("DSP.out",7168) ;

                                    /*   //gui_about("I am a test value","1.0.01");
                                               printf("START button Pressed\n");
                                               //UART(); // nirs
                                               //UART3();        // eeg data
                                               CallApp("/sound/start.sh");
                                               printf("START DONE! \n");
                                       break;  */

                                       case REC:
                                               printf("\nEXE button Pressed\n");
                                            // vol_Control_Msg();
                                             LOOP_Execute () ;
                                               //sendControlMsg( MSGNEWVOL, 1, val );
                                              
                                               //Draw_Graph();
                                              // plot_200x200(1);
                                              /* argc = 4;
                                               argv[0] = "wav_rec_rf6_gpp1";
                                               argv[1] = "wav_rec_rf6_dsp.out";
                                               argv[2] = "ISIP.wav";
                                               argv[3] = "44100";*/

                                              // wave_rec_main();
                                               //CallApp("/sound/rec.sh");
                                              // printf("RECORDING STARTED! \n");
                                       break; 

                                       case STOP:
                                               printf("\nSTOP button Pressed\n");
                                               printf( "\n Leaving Reference Framework 6 audio application\n\n" );
                                              // stop_Appl();
                                               LOOP_Delete () ;
                                               //terminateAppl( "Clean-up completed.", 7 ) ;
                               
       
                                               //CallApp("/sound/stop.sh");
                                               //printf("RECORDING STOPPED!\n");
                                       break;
                                             

                                     /*  case PLAY:
                                               printf("PLAY button Pressed\n");
                                               // copy the background of the screen
                                               //CopyScreen(background,0,0,SCREEN_WIDTH,SCREEN_HEIGHT);
                                               //call save data bash file
                                               CallApp("/sound/play.sh");
                                               printf("PLAYING.. \n");
                                               // paste the background screen
                                               //PasteScreen(background,0,0,SCREEN_WIDTH,SCREEN_HEIGHT);
                                               break; */

					
										
					default:
						DefaultMessageRoutine(frmSample,&msg);

				} // end of EVENT_CLICK
			break;
			
			default:
				DefaultMessageRoutine(frmSample,&msg);
		}	
	}  /**** end of message loop *****/
 } 
 
